num_workers: 4
batch_size: 1000

# Memory map просто чтобы можно было idx получить и использовать как client_id

dataset:
  _target_: ptls_extension_2024_research.frames.inference_module_client_id_aware.dataset_with_id.DatasetWithId
  data:
    _target_: ptls.data_load.datasets.MemoryMapDataset
    data:
      _target_: ptls.data_load.datasets.ParquetDataset
      data_files:
        _target_: ptls.data_load.datasets.ParquetFiles
        file_path:
          - data/train_trx.parquet
          - data/test_trx.parquet
      i_filters:
        - _target_: ptls.data_load.iterable_processing.FeatureFilter
          keep_feature_names: customer_id
        - _target_: ptls.data_load.iterable_processing.ISeqLenLimit
          max_seq_len: 2000

output:
  path: data/${embed_file_name}
  format: pickle