defaults:
  - _self_
  - dataset_unsupervised/parquet
  - inference/smaller_for_check.yaml
  - inference/seq_encoder/pretrained

seed_everything: 42
logger_name: coles_gnn_model
model_path: models/coles_gnn_model.p
embed_file_name: coles_gnn_embeddings

data_module:
  _target_: ptls.frames.PtlsDataModule
  train_data:
    _target_: ptls_extension_2024_research.ColesDataset
    splitter:
      _target_: ptls.frames.coles.split_strategy.SampleSlices
      split_count: 5
      cnt_min: 15
      cnt_max: 75
    data: ${dataset_unsupervised.train}
  valid_data:
    _target_: ptls.frames.coles.ColesDataset
    splitter:
      _target_: ptls.frames.coles.split_strategy.SampleSlices
      split_count: 5
      cnt_min: 25
      cnt_max: 100
    data: ${dataset_unsupervised.valid}
  train_batch_size: 128
  train_num_workers: 8
  valid_batch_size: 1024
  valid_num_workers: 16

trainer: 
  accelerator: gpu
  max_epochs: 150
  enable_checkpointing: false
  deterministic: true

pl_module:
  _target_: ptls_extension_2024_research.frames.coles_gnn.coles_gnn_module.ColesGnnModuleFullGraph
  seq_encoder:
    _target_: ptls.nn.RnnSeqEncoder
    trx_encoder: 
      _target_: ptls_extension_2024_research.TrxEncoder_WithCIEmbeddings
      norm_embeddings: false
      embeddings_noise: 0.003
      embeddings:
        mcc_code:
          in: 200
          out: 48
        tr_type:
          in: 100
          out: 24
      numeric_values: 
        amount: identity
      col_item_ids: mcc_code
      
      client_item_embeddings:
        _target_: ptls_extension_2024_research.hydra_utils.kwargs_to_list
        gnn_ci_embedder:
          _target_: ptls_extension_2024_research.nn.trx_encoder.client_item_encoder.StaticGNNTrainableClientItemEncoder
          data_adapter:
            _target_: ptls_extension_2024_research.frames.gnn.gnn_module.ColesBatchToSubgraphConverterFull
            # graph_file_path: data/graphs/unweighted/full_graph.bin
            # item_id2graph_id_path: data/graphs/unweighted/item_id2graph_id_path.pt
            # client_id2graph_id_path: data/graphs/unweighted/client_id2graph_id_path.pt
            graph_file_path: data/graphs/weighted/full_graph.bin
            item_id2graph_id_path: data/graphs/weighted/item_id2graph_id.pt
            client_id2graph_id_path: data/graphs/weighted/client_id2graph_id.pt
          gnn_link_predictor: 
            _target_: ptls_extension_2024_research.frames.gnn.gnn_module.GnnLinkPredictor
            n_users: 15000
            n_items: 184
            output_size: 10
            embedding_dim: 64
            train_client_embeddings: True
            train_item_embeddings: True
            link_predictor_name: MLP
            link_predictor_add_sigmoid: True
            gnn_name: GraphSAGE
            gnn_kwargs_dict:
              num_layers: 1
    type: gru
    hidden_size: 1024
    bidir: false
    trainable_starter: static
  coles_head:
    _target_: ptls.nn.Head
    use_norm_encoder: true
    input_size: ${pl_module.seq_encoder.hidden_size}
  coles_loss:
    _target_: ptls.frames.coles.losses.ContrastiveLoss
    margin: 0.5
    sampling_strategy:
      _target_: ptls.frames.coles.sampling_strategies.HardNegativePairSelector
      neg_count: 5
  coles_validation_metric:
    _target_: ptls.frames.coles.metric.BatchRecallTopK
    K: 4
    metric: cosine
  rand_edge_sampler_seed: 42
  neg_items_per_pos: 1
  lp_criterion_name: 'BCELoss'
  optimizer_partial:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 0.002
    weight_decay: 0.0
  lr_scheduler_partial:
    _partial_: true
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 10
    gamma: 0.9025





