conf_path: conf/embeddings_validation_baselines_unsupervised.yaml
environment: 
  work_dir: embeddings_validation.work
target: 
  file_name: ${hydra:runtime.cwd}/data/gender_train.csv
  cols_id: 
    - customer_id
  cols_id_type: 
    - int
  col_target: gender
split: 
  fit_ids: true
  train_id: 
    file_name: ${hydra:runtime.cwd}/data/gender_train.csv
  test_id: 
    file_name: ${hydra:runtime.cwd}/data/test_ids.csv
  cv_split_count: 5
  is_stratify: true
  random_state: 42
models: 
  linear: 
    enabled: false
    model:
      _target_: sklearn.linear_model.LogisticRegression
    cpu_count: 1
    preprocessing: 
      - _target_: sklearn.preprocessing.MaxAbsScaler

  lgbm: 
    enabled: true
    model:
      _target_: lightgbm.LGBMClassifier
      n_estimators: 500
      boosting_type: gbdt
      objective: binary
      metric: auc
      subsample: 0.5
      subsample_freq: 1
      learning_rate: 0.02
      feature_fraction: 0.75
      max_depth: 6
      lambda_l1: 1
      lambda_l2: 1
      min_data_in_leaf: 50
      random_state: 42
      n_jobs: 8
      reg_alpha: null
      reg_lambda: null
      colsample_bytree: null
      min_child_samples: null
    cpu_count: 4
    preprocessing: 
      - _target_: sklearn.preprocessing.MaxAbsScaler

  xgb: 
    enabled: false
    model:
      _target_: xgboost.XGBClassifier
      n_jobs: 4
      seed: 42
      n_estimators: 300
    cpu_count: 4
    preprocessing: 
      - _target_: sklearn.preprocessing.MaxAbsScaler

metrics: 
  auroc: 
    enabled: true
    score_func: sklearn.metrics.roc_auc_score
    scorer_params: 
      needs_proba: true
  accuracy: 
    enabled: true
    score_func: sklearn.metrics.accuracy_score
    scorer_params: 
      needs_proba: false
report_file: ${hydra:runtime.cwd}/results/scenario_gender_2024_research.txt
features: 
  # coles_avg_pool: 
  #   enabled: true
  #   read_params: 
  #     file_name: ${hydra:runtime.cwd}/data/coles_avg_pool_model_embeddings.pickle
  #   target_options: {}
  # coles: 
  #   enabled: true
  #   read_params: 
  #     file_name: ${hydra:runtime.cwd}/data/mles_model_small_batch_2_embeddings.pickle
  #   target_options: {}
 coles_gnn_0_5_w_pred_bce__has_orig:
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/coles_gnn_weighted__w_pred_bce__has_orig.pickle
    target_options: {}
 coles_gnn_0_9_w_pred_mse__has_orig: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/coles_gnn_weighted__w_pred_mse__has_orig.pickle
    target_options: {}

 coles_gnn_0_5_w_pred_bce__no_orig:
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/coles_gnn_weighted__w_pred_bce__no_orig_embeddings.pickle
    target_options: {}
 coles_gnn_0_9_w_pred_mse__no_orig: 
    enabled: true
    read_params: 
      file_name: ${hydra:runtime.cwd}/data/coles_gnn_weighted__w_pred_mse__no_orig_embeddings.pickle
    target_options: {}
external_scores: {}
report: 
  is_check_train: false
  error_handling: fail
  print_all_metrics: false
  metrics: 
    auroc: 
      float_format: "{:.3f}"
      baseline_key: 
        - lgbm
        # - coles
      split_columns: true
    accuracy: 
      float_format: "{:.3f}"
      baseline_key: 
        - lgbm
        # - coles
      split_columns: true
