defaults:
  - _self_
  - dataset_unsupervised/parquet
  - inference/smaller_for_check.yaml
  - inference/seq_encoder/pretrained

seed_everything: 42
logger_name: coles_gnn_check__model
model_path: models/coles_gnn_check__model.p
embed_file_name: coles_gnn_check__embeddings

data_module:
  _target_: ptls.frames.PtlsDataModule
  train_data:
    _target_: coles_and_gnn_frame.ColesDataset
    splitter:
      _target_: ptls.frames.coles.split_strategy.SampleSlices
      split_count: 5
      cnt_min: 25
      cnt_max: 200
    data: ${dataset_unsupervised.train}
  valid_data:
    _target_: ptls.frames.coles.ColesDataset
    splitter:
      _target_: ptls.frames.coles.split_strategy.SampleSlices
      split_count: 5
      cnt_min: 25
      cnt_max: 100
    data: ${dataset_unsupervised.valid}
  train_batch_size: 32
  train_num_workers: 4
  valid_batch_size: 32
  valid_num_workers: 4

trainer: 
  accelerator: gpu
  max_epochs: 150
  enable_checkpointing: false
  deterministic: true

pl_module:
  _target_: coles_and_gnn_frame.CoLESModuleMyTrx
  validation_metric:
    _target_: ptls.frames.coles.metric.BatchRecallTopK
    K: 4
    metric: cosine
  seq_encoder:
    _target_: ptls.nn.RnnSeqEncoder
    trx_encoder:
      _target_: coles_and_gnn_frame.TrxEncoder_WithClientIds
      norm_embeddings: false
      embeddings_noise: 0.003
      embeddings:
        trans_date:
          in: 800
          out: 16
        small_group:
          in: 250
          out: 16
      numeric_values: 
        amount_rur: identity
      # col_item_ids: small_group
      # client_item_embeddings: [coles_and_gnn_frame.DummyClientItemEmbeddings]
    type: gru
    hidden_size: 800
    bidir: false
    trainable_starter: static
  head:
    _target_: ptls.nn.Head
    use_norm_encoder: true
  loss:
    _target_: ptls.frames.coles.losses.ContrastiveLoss
    margin: 0.5
    sampling_strategy:
      _target_: ptls.frames.coles.sampling_strategies.HardNegativePairSelector
      neg_count: 5
  optimizer_partial:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 0.001
    weight_decay: 0.0
  lr_scheduler_partial:
    _partial_: true
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 30
    gamma: 0.9025
