defaults:
  - _self_
  - dataset_unsupervised/parquet
  - inference/default
  - inference/seq_encoder/pretrained

seed_everything: 42
logger_name: mles_model
model_path: models/mles_model.p
embed_file_name: mles_embeddings

data_module:
  _target_: ptls.frames.PtlsDataModule
  train_data:
    _target_: ptls.frames.coles.ColesIterableDataset
    splitter:
      _target_: ptls.frames.coles.split_strategy.SampleSlices
      split_count: 5
      cnt_min: 25
      cnt_max: 200
    data: ${dataset_unsupervised.train}
  valid_data:
    _target_: ptls.frames.coles.ColesIterableDataset
    splitter:
      _target_: ptls.frames.coles.split_strategy.SampleSlices
      split_count: 5
      cnt_min: 25
      cnt_max: 100
    data: ${dataset_unsupervised.valid}
  train_batch_size: 64
  train_num_workers: 16
  valid_batch_size: 512
  valid_num_workers: 16

trainer: 
  accelerator: gpu
  max_epochs: 150
  enable_checkpointing: false
  deterministic: true

pl_module:
  _target_: ptls.frames.coles.CoLESModule
  validation_metric:
    _target_: ptls.frames.coles.metric.BatchRecallTopK
    K: 4
    metric: cosine
  seq_encoder:
    _target_: ptls.nn.RnnSeqEncoder
    trx_encoder:
      _target_: ptls.nn.TrxEncoder
      norm_embeddings: false
      embeddings_noise: 0.003
      embeddings:
        region_name:
          in: 81
          out: 8
        city_name:
          in: 985
          out: 8
        cpe_model_name:
          in: 599
          out: 8
        cpe_manufacturer_name:
          in: 37
          out: 8
        part_of_day:
          in: 4
          out: 8
        cpe_type_cd:
          in: 4
          out: 8
        cpe_model_os_type:
          in: 3
          out: 8
      numeric_values: 
        price: identity
        request_cnt: identity
    type: gru
    hidden_size: 800
    bidir: false
    trainable_starter: static
  head:
    _target_: ptls.nn.Head
    use_norm_encoder: true
  loss:
    _target_: ptls.frames.coles.losses.ContrastiveLoss
    margin: 0.5
    sampling_strategy:
      _target_: ptls.frames.coles.sampling_strategies.HardNegativePairSelector
      neg_count: 5
  optimizer_partial:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 0.001
    weight_decay: 0.0
  lr_scheduler_partial:
    _partial_: true
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 30
    gamma: 0.9025
